### ISSUE TITLE
deploy yaml error 

### ISSUE THREAD

**Issue by waney316** [apache/rocketmq-operator#107]
p1：role.yaml and role_binding.yaml name properties do not match，ClusterRoleBinding namespace should not specify default

```yaml
---
# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role    # not match
```
```yaml
# role_binding.yaml 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rocketmq-operator
subjects:
- kind: ServiceAccount
  name: rocketmq-operator
  namespace: default  
roleRef:
  kind: ClusterRole
  name: rocketmq-operator   # not match
  apiGroup: rbac.authorization.k8s.io
```

p2：manager running error，role.yaml missing some permissions defined
- get configmap is forbiden
- get  resources not found 

![image](https://user-images.githubusercontent.com/23314093/176985417-835b3759-1d06-4639-be3b-acf8a9a1c746.png)

p3：use lastest code create crd to cluster，api-resources and role.yaml do not match
![image](https://user-images.githubusercontent.com/23314093/176985503-7f281760-a0f3-4043-97ae-4126da60a788.png)
![image](https://user-images.githubusercontent.com/23314093/176985528-ed3a7ae7-a59d-4214-89ea-a721acb872c1.png)
