### ISSUE TITLE
:rocketmq-operator" cannot get resource "leases

### ISSUE THREAD

**Issue by feiyuyitiao** [apache/rocketmq-operator#113]
after `make deploy`

check operator log,  which prints: 
```
E0712 08:48:26.825666       1 leaderelection.go:330] error retrieving resource lock default/2516c052.apache.org: leases.coordination.k8s.io "2516c052.apache.org" is forbidden: User "system:serviceaccount:default:rocketmq-operator" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "default"
```

**Comment by feiyuyitiao** [comment]
fix by add 'ClusterRole'  leases.

**Comment by feiyuyitiao** [comment]
fix by add 'ClusterRole' leases.

**Comment by feiyuyitiao** [comment]
fix by add 'ClusterRole' leases.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question` | Status: **Answered**

This is an RBAC permission issue. The operator needs access to `leases` resources for leader election, but the `ClusterRole` does not include this permission.

**Fix:** Add the following to your `role.yaml`:
```yaml
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
```

Then re-apply the role and role binding.

---
*Automated evaluation by github-manager*
