### ISSUE TITLE
the 'console'  create  failed.

### ISSUE THREAD

**Issue by feiyuyitiao** [apache/rocketmq-operator#114]
operator got error when apply console.yaml
```
2022-07-12T10:58:11.493Z        ERROR   controller.console-controller   Reconciler error        {"name": "console", "namespace": "mq", 
"error": "Deployment.apps \"console\" is invalid: spec.template.metadata.labels: Invalid value: map[string]string(nil): `selector` does not match template `labels`"}
```

**Comment by caigy** [comment]
@feiyuyitiao Is `spec.template.metadata.labels` defined in `console.yaml`?

**Comment by feiyuyitiao** [comment]
fix by change code:  pkg/controller/console/console_controller.go:201
`					//Labels: cr.Spec.ConsoleDeployment.Spec.Template.ObjectMeta.Labels,
					Labels: cr.Spec.ConsoleDeployment.Spec.Selector.MatchLabels,  `

**Comment by ccctask** [comment]
same issue with me 😯

**Comment by ccctask** [comment]
`rocketmq-operator/example/rocketmq_v1alpha1_rocketmq_cluster.yaml` with example  resources define
```yaml
apiVersion: rocketmq.apache.org/v1alpha1
kind: Console
metadata:
  name: console
spec:
  # nameServers is the [ip:port] list of name service
  nameServers: ""
  # consoleDeployment define the console deployment
  consoleDeployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rocketmq-console
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rocketmq-console
      template:
        metadata:
          labels:
            app: rocketmq-console
        spec:
          containers:
            - name: console
              image: apacherocketmq/rocketmq-console:2.0.0
              ports:
                - containerPort: 8080
```
