### ISSUE TITLE
How to use tolerations , nodeSelector and nodeAffinity features

### ISSUE THREAD

**Issue by se7vet** [apache/rocketmq-operator#122]
In our scenario, rocketmq needs to use a unique node，How to use tolerations , nodeSelector and nodeAffinity features ,  like this is invalid. 
```
apiVersion: rocketmq.apache.org/v1alpha1
kind: Broker
metadata:
  name: broker
spec:
  size: 1
  nameServers: ""
  replicaPerGroup: 1
  brokerImage: rocketmq-broker:4.5.0-alpine-operator-0.3.0
  imagePullPolicy: Always
  tolerations:
    - key: "key"
      value: "value"
      operator: "Equal"
      effect: "NoSchedule"
  nodeSelector:
    key: "value"
...
```

**Comment by caigy** [comment]
@se7vet Pls provide detailed error messages.

**Comment by caigy** [comment]
@se7vet If you want to deploy only one broker in one host, you may define podAntiAffinity policy like this:
```yaml
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: broker
            topologyKey: kubernetes.io/hostname
```
