### ISSUE TITLE
console doesn't support affinity filed

### ISSUE THREAD

**Issue by chaoyoung** [apache/rocketmq-operator#142]
rocketmq_cluster.yaml
```yaml
apiVersion: rocketmq.apache.org/v1alpha1
kind: Console
metadata:
  name: console
  namespace: rocketmq
spec:
  # nameServers is the [ip:port] list of name service
  nameServers: ""
  # consoleDeployment define the console deployment
  consoleDeployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: rocketmq-console
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: rocketmq-console
      template:
        metadata:
          labels:
            app: rocketmq-console
        spec:
          containers:
            - name: console
              image: apacherocketmq/rocketmq-dashboard:1.0.0
              ports:
                - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dev-k8s-node1
                - dev-k8s-node2
```

kubectl apply -f rocketmq_cluster.yaml
```
error: error validating "rocketmq_v1alpha1_rocketmq_cluster.yaml": error validating data: ValidationError(Console.spec.consoleDeployment.spec): unknown field "affinity" in org.apache.rocketmq.v1alpha1.Console.spec.consoleDeployment.spec; if you choose to ignore these errors, turn validation off with --validate=false
```
