### ISSUE TITLE
Cannot access name-service by kubernetes Service

### ISSUE THREAD

**Issue by chaoyoung** [apache/rocketmq-operator#145]
After setting the network of name-server to non-host mode, the name-service cannot be accessed by adding Service，the address `rocketmq-console.rocketmq.svc.cluster.local` can be pinged, but telnet fails, prompt Connection refused.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: name-service
  namespace: rocketmq
  labels:
    app: name-service
spec:
  type: ClusterIP
  selector:
    app: name-service
  ports:
  - name: main
    port: 80
    protocol: TCP
    targetPort: 9876
```
