### ISSUE TITLE
Controller pod controllerDLegerPeers wrong address

### ISSUE THREAD

**Issue by drivebyer** [apache/rocketmq-operator#193]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
apply cr:
```
apiVersion: rocketmq.apache.org/v1alpha1
kind: Controller
metadata:
  name: rmq-wy-controller
  namespace: mcamel-system
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app: controller
              controller_cr: rmq-wy-controller-controller
          topologyKey: kubernetes.io/hostname
        weight: 60
  controllerImage: ghcr.m.daocloud.io/ksmartdata/rocketmq-controller:v5.1.4
  hostPath: /data/rocketmq/controller
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  size: 1
  storageMode: EmptyDir
  volumeClaimTemplates:
  - metadata:
      name: controller-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 8Gi
    status: {}
```

- What did you expect to see?
the k8s create pod with such environment:
```
    - name: controllerDLegerPeers
       value: rmq-wy-controller0-rmq-wy-controller-0.rmq-wy-controller-svc-headless:9878
```

The address is wrong:
<img width="713" alt="截屏2023-11-16 16 48 47" src="https://github.com/apache/rocketmq-operator/assets/32033618/36a8409e-00fa-444e-a553-b1960a29b3ef">

- What did you see instead?
the address should be `rmq-wy-controller-0.rmq-wy-controller-svc-headless`, see:
<img width="760" alt="截屏2023-11-16 16 49 58" src="https://github.com/apache/rocketmq-operator/assets/32033618/2d91090b-4a9d-480f-95aa-0b7a48d25421">

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
