### ISSUE TITLE
Unable to set environment variables in NameServer pod.

### ISSUE THREAD

**Issue by shangjin92** [apache/rocketmq-operator#207]
There are some circumstances where setting environment variables in the NameServer pod is necessary, such as when addressing the CVE-2011-1473 vulnerability, which requires the addition of specific environment variables.

```yaml
env:
    - name: JAVA_OPT_EXT
      value: " -Djdk.tls.rejectClientInitiatedRenegotiation=true "
```

CVE-2011-1473：
* https://cve.mitre.org/cgi-bin/cvename.cgi?name=cve-2011-1473
* https://nvd.nist.gov/vuln/detail/CVE-2011-1473
* https://github.com/apache/rocketmq/issues/1233
