### ISSUE TITLE
rocketmq开启acl后plain_acl.yml这个文件如何持久化

### ISSUE THREAD

**Issue by wolf27w** [apache/rocketmq-operator#215]
我是在k8s中部署的rockermq，但是开启acl后，plain_acl.yml这个文件是在conf目录下，我无法映射出来或者修改plain_acl.yml文件的路径，请问一下有其他的方法吗？

**Comment by caigy** [comment]
duplicated with #184

**Comment by caigy** [comment]
@wolf27w 目前尚未支持，#200 仍在开发中。可以看看这个方法是否能临时解决？https://github.com/apache/rocketmq-operator/issues/184#issuecomment-1750292679

**Comment by wolf27w** [comment]
明白了，我看他写的有点错误，应该把configmap里的plain_acl.yml替换到/home/rocketmq/rocketmq-4.9.7/conf/plain_acl.yml才是正确的，不需要在开发了

**Comment by bugsmo** [comment]
挂载自定义ACL有了新的姿势。
1. 创建acl configmap，`kubectl create configmap broker-acl --from-file=plain_acl.yml=plain_acl.yml`
2. broker cr配置acl configmap，`kubectl edit brokers.rocketmq.apache.org rocketmq-cluster-test`
```yaml
apiVersion: rocketmq.apache.org/v1alpha1
kind: Broker
...
spec:
volumes:
  - configMap:
      name: broker-acl
    name: broker-acl
```

3. sts挂载acl configmap到pod。`kubectl edit statefulsets.apps rocketmq-cluster-test-0-0`
```yaml
apiVersion: apps/v1
kind: StatefulSet
...
spec:
  volumes:
  - configMap:
          defaultMode: 420
          name: broker-acl
        name: broker-acl
  containers:
    volumeMounts:
    - mountPath: /root/rocketmq/broker/conf/acl
          name: broker-acl
```

可以实现acl配置热加载。

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `question`

To persist `plain_acl.yml` in Kubernetes:
1. Create a ConfigMap with your ACL configuration
2. Mount it as a volume in the broker StatefulSet, overriding the default `conf/plain_acl.yml`

Example:
```yaml
# In your Broker CR or StatefulSet template
volumeMounts:
  - name: acl-config
    mountPath: /home/rocketmq/rocketmq-4.9.4/conf/plain_acl.yml
    subPath: plain_acl.yml
volumes:
  - name: acl-config
    configMap:
      name: broker-acl-config
```

Alternatively, check if the operator CRD supports an `aclConfigMap` field in newer versions.

---
*Automated evaluation by RockteMQ-AI*
