### ISSUE TITLE
broker OOMKilled

### ISSUE THREAD

**Issue by carloscao0928** [apache/rocketmq-operator#36]
先贴下我的配置：
![5](https://user-images.githubusercontent.com/58930323/90315069-f50c0100-df4a-11ea-85c9-3db617ab6dca.png)
![6](https://user-images.githubusercontent.com/58930323/90315071-fb01e200-df4a-11ea-8c20-b0b9a65e3747.png)
![7](https://user-images.githubusercontent.com/58930323/90315073-005f2c80-df4b-11ea-8488-2b5e1cc0713e.png)

nameservice 可以启动，但broker不行，查看logs的话
![QQ截图20200815225237](https://user-images.githubusercontent.com/58930323/90314947-14eef500-df4a-11ea-8132-388c519ebbd3.png)

describe的话，结果如下：
![1](https://user-images.githubusercontent.com/58930323/90314981-4e276500-df4a-11ea-9902-c454c6d93066.png)
![2](https://user-images.githubusercontent.com/58930323/90314985-57183680-df4a-11ea-9366-6b2616ed7516.png)

不知道怎么处理，谢谢

**Comment by liuruiyiyang** [comment]
It seems that the broker is ```OOMKilled```. Could you please try to use the default configuration of broker CR:
```
resources:
    requests:
      memory: "2048Mi"
      cpu: "250m"
    limits:
      memory: "4096Mi"
      cpu: "500m"
```
and see if it works.

Thanks for your feedback!

**Comment by carloscao0928** [comment]
> 看来经纪人是`OOMKilled`。您能否尝试使用代理CR的默认配置：
> 
> ```
> resources:
>     requests:
>       memory: "2048Mi"
>       cpu: "250m"
>     limits:
>       memory: "4096Mi"
>       cpu: "500m"
> ```
> 
> 看看是否可行。
> 
> 感谢您的反馈意见！

我就是先用默认的报错 才加大内存和cpu，发现还是报错，所以提交下问题

**Comment by liuruiyiyang** [comment]
Does your environment has the requested resource of memory?  Maybe you should try smaller resource like  
```
resources:
    requests:
      memory: "1024Mi"
      cpu: "250m"
    limits:
      memory: "2048Mi"
      cpu: "500m"
```

**Comment by liuruiyiyang** [comment]
> > 看来经纪人是`OOMKilled`。您能否尝试使用代理CR的默认配置：
> > ```
> > resources:
> >     requests:
> >       memory: "2048Mi"
> >       cpu: "250m"
> >     limits:
> >       memory: "4096Mi"
> >       cpu: "500m"
> > ```
> > 
> > 
> > 看看是否可行。
> > 感谢您的反馈意见！
> 
> 我就是先用默认的报错 才加大内存和cpu，发现还是报错，所以提交下问题

Is the default config also ```OOMKilled``` ?

**Comment by carloscao0928** [comment]
> > > 看来经纪人是`OOMKilled`。您能否尝试使用代理CR的默认配置：
> > > ```
> > > resources:
> > >     requests:
> > >       memory: "2048Mi"
> > >       cpu: "250m"
> > >     limits:
> > >       memory: "4096Mi"
> > >       cpu: "500m"
> > > ```
> > > 
> > > 
> > > 看看是否可行。
> > > 感谢您的反馈意见！
> > 
> > 
> > 我就是先用默认的报错 才加大内存和cpu，发现还是报错，所以提交下问题
> 
> Is the default config also `OOMKilled` ?

![捕获](https://user-images.githubusercontent.com/58930323/90390876-b39c6280-e0be-11ea-80c8-893c8fb4395d.PNG)


不起作用

**Comment by liuruiyiyang** [comment]
@carloscao0928 你试了把request 和limits 内存再调小一点吗？ 如果还不行是否是你的服务器内存不够或者docker对容器内存有什么限制？

Have you tried configure smaller memory resource? If still not work please check if your host has enough memory or your docker has some restrains on container memory resource.

**Comment by carloscao0928** [comment]
> @carloscao0928 你试了把request 和limits 内存再调小一点吗？ 如果还不行是否是你的服务器内存不够或者docker对容器内存有什么限制？
> 
> Have you tried configure smaller memory resource? If still not work please check if your host has enough memory or your docker has some restrains on container memory resource.

试过了没有用，服务器够的，12cpu 48gram，容器也没有限制

**Comment by liuruiyiyang** [comment]
Currently the broker startup script use ```max(min(1/2 ram, 1024MB), min(1/4 ram, 8GB))``` to calculate JVM max heap size.
Try to set request memory more than 8GB? like:
```
resources:
    requests:
      memory: "10240Mi"
      cpu: "250m"
    limits:
      memory: "14240Mi"
      cpu: "500m"
```
